# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-05 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0002_auto_20170930_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
